server:
  port: 8080


  servlet:
    session:
      timeout: 60

spring:
  application:
    name: springsecruity
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 10.10.4.76
    port: 6379
    database: 1
  session:
    store-type: redis